# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'puma', '~> 6.0'
gem 'rack-cors', '~> 2.0'
gem 'ruby-openai', '~> 7.0'
gem 'dotenv', '~> 3.1'
gem 'json'
gem 'rackup'
gem 'sinatra-contrib', '~> 4.0'

group :test do
  gem 'rspec', '~> 3.13'
  gem 'rack-test', '~> 2.1'
  gem 'webmock', '~> 3.23'
end
